### ISSUE TITLE
Create actor for gathering the data about PCI devices with the limitted support

### ISSUE THREAD

**Issue by zhukovgreen** [oamg/leapp-repository#595]
Ref #593 

Acceptance criteria:
- [x] env var LEAPP_DEVEL_PCIS_HOST implemented and used #601
- [x] in case the microservice is not accessible (i.e. offline installation) a local copy of the data should be used #601
- [x] in case the local copy of the data is used - warn the user about the risk of outdated data #601
- [x] document the new env var https://github.com/oamg/leapp/pull/668

**Comment by pirat89** [comment]
This has been done
